---
# tasks file for apache

-  name: install apache
   yum:
     name: httpd
     state: latest
   notify:
   -  enable and start apache

-  name: enable firewall
   firewalld:
     service: http
     state: enabled
     permanent: yes
     immediate: yes

-  name: copy over the template file
   template:
     src: domain.j2
     dest: "/etc/httpd/conf.d/vhost.conf"




